version: '3.3'
services:
  ###############################################################################
  # Redis
  ###############################################################################
  redis:
    image: redis:5
    expose:
      - '$REDIS_PORT'
    volumes:
      - './data/redis:/data'
    command:
      - 'bash'
      - '-c'
      - 'docker-entrypoint.sh --requirepass $AUTHENTICATOR_TOKEN_DB_PASSWORD'
    networks:
      - net
  ###############################################################################
  # Mongo
  ###############################################################################
  mongo:
    image: mongo:4.4
    expose:
      - '$MONGO_PORT'
    volumes:
      - './data/mongodb:/data/db'
      - './backup:/backup'
    networks:
      - net
  ###############################################################################
  # Gateway
  ###############################################################################
  gateway:
    image: mre/gateway:latest
    environment:
      - NODE_ENV
      - LOGGER_LEVEL=$LOGGER_LEVEL
      - PORT=$GATEWAY_PORT
      - EXPOSE_FRONTENDS=$GATEWAY_EXPOSE_FRONTENDS
      - AUTHENTICATOR_PORT=$AUTHENTICATOR_PORT
      - API_PORT=$API_PORT
      - PDFGENERATOR_PORT=$PDFGENERATOR_PORT
      - LANDLORD_FRONTEND_PORT=$LANDLORD_FRONTEND_PORT
      - LANDLORD_BASE_PATH=$LANDLORD_BASE_PATH
      - TENANT_FRONTEND_PORT=$TENANT_FRONTEND_PORT
      - TENANT_BASE_PATH=$TENANT_BASE_PATH
      - DOMAIN_URL=$DOMAIN_URL
      - CORS_ENABLED=$CORS_ENABLED
    ports:
      - '$GATEWAY_PORT:$GATEWAY_PORT'
    networks:
      - net
    depends_on:
      - authenticator
      - api
      - pdfgenerator
  ###############################################################################
  # Authenticator
  ###############################################################################
  authenticator:
    image: mre/authenticator:latest
    environment:
      - NODE_ENV
      - PORT=$AUTHENTICATOR_PORT
      - LOGGER_LEVEL=$LOGGER_LEVEL
      - TOKEN_DB_URL=$AUTHENTICATOR_TOKEN_DB_URL
      - TOKEN_DB_PASSWORD=$AUTHENTICATOR_TOKEN_DB_PASSWORD
      - ACCESS_TOKEN_SECRET=$AUTHENTICATOR_ACCESS_TOKEN_SECRET
      - REFRESH_TOKEN_SECRET=$AUTHENTICATOR_REFRESH_TOKEN_SECRET
      - RESET_TOKEN_SECRET=$AUTHENTICATOR_RESET_TOKEN_SECRET
      - BASE_DB_URL=$BASE_DB_URL
      - EMAILER_URL=$EMAILER_URL
      - SIGNUP=$SIGNUP
      - DOMAIN_URL=$DOMAIN_URL
    expose:
      - '$AUTHENTICATOR_PORT'
    networks:
      - net
    depends_on:
      - redis
      - mongo
      - emailer
  ###############################################################################
  # PDFGenerator
  ###############################################################################
  pdfgenerator:
    image: mre/pdfgenerator:latest
    environment:
      - NODE_ENV
      - PORT=$PDFGENERATOR_PORT
      - LOGGER_LEVEL=$LOGGER_LEVEL
      - MONGO_URL=$BASE_DB_URL
      - ACCESS_TOKEN_SECRET=$AUTHENTICATOR_ACCESS_TOKEN_SECRET
      - CIPHER_KEY=$CIPHER_KEY
      - CIPHER_IV_KEY=$CIPHER_IV_KEY
    expose:
      - '$PDFGENERATOR_PORT'
    networks:
      - net
    depends_on:
      - mongo
  ###############################################################################
  # Emailer
  ###############################################################################
  emailer:
    image: mre/emailer:latest
    environment:
      - NODE_ENV
      - ALLOW_SENDING_EMAILS=$ALLOW_SENDING_EMAILS
      - PORT=$EMAILER_PORT
      - LOGGER_LEVEL=$LOGGER_LEVEL
      - APP_NAME=$APP_NAME
      - LANDLORD_APP_URL=$LANDLORD_APP_URL
      - TENANT_APP_URL=$TENANT_APP_URL
      - MONGO_URL=$BASE_DB_URL
      - ACCESS_TOKEN_SECRET=$AUTHENTICATOR_ACCESS_TOKEN_SECRET
      - CIPHER_KEY=$CIPHER_KEY
      - CIPHER_IV_KEY=$CIPHER_IV_KEY
      - PDFGENERATOR_URL=$PDFGENERATOR_URL
      - MAILGUN_API_KEY=$MAILGUN_API_KEY
      - MAILGUN_DOMAIN=$MAILGUN_DOMAIN
      - EMAIL_FROM=$EMAIL_FROM
      - EMAIL_REPLY_TO=$EMAIL_REPLY_TO
      - EMAIL_BCC=$EMAIL_BCC
    expose:
      - '$EMAILER_PORT'
    networks:
      - net
    depends_on:
      - mongo
      - pdfgenerator
  ###############################################################################
  # api
  ###############################################################################
  api:
    image: mre/api:latest
    volumes:
      - ./backup:/usr/app/backup
    environment:
      - NODE_ENV
      - PORT=$API_PORT
      - LOGGER_LEVEL=$LOGGER_LEVEL
      - SIGNUP=$SIGNUP
      - MONGO_URL=$BASE_DB_URL
      - DEMO_MODE=$DEMO_MODE
      - EMAILER_URL=$EMAILER_URL
      - PDFGENERATOR_URL=$PDFGENERATOR_URL
      - RESTORE_DB=$RESTORE_DB
      - ACCESS_TOKEN_SECRET=$AUTHENTICATOR_ACCESS_TOKEN_SECRET
      - CIPHER_KEY=$CIPHER_KEY
      - CIPHER_IV_KEY=$CIPHER_IV_KEY
    expose:
      - '$API_PORT'
    networks:
      - net
    depends_on:
      - mongo
      - emailer
      - pdfgenerator
  ###############################################################################
  # Landlord frontend
  ###############################################################################
  landlord-frontend:
    build:
      args:
        - BASE_PATH=$LANDLORD_BASE_PATH
    image: mre/landlord-frontend:latest
    environment:
      - NODE_ENV
      - PORT=$LANDLORD_FRONTEND_PORT
      - LOGGER_LEVEL=$LOGGER_LEVEL
      - APP_NAME=$APP_NAME
      - BASE_PATH=$LANDLORD_BASE_PATH
      - API_URL=$API_URL
      - APP_URL=$LANDLORD_APP_URL
      - DOCKER_API_URL=$DOCKER_API_URL
      - REFRESH_TOKEN_SECRET=$AUTHENTICATOR_REFRESH_TOKEN_SECRET
      - DEMO_MODE=$DEMO_MODE
      - SIGNUP=$SIGNUP
      - CORS_ENABLED=$CORS_ENABLED
    expose:
      - '$LANDLORD_FRONTEND_PORT'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - net
    depends_on:
      - gateway
  ###############################################################################
  # Tenant frontend
  ###############################################################################
  tenant-frontend:
    build:
      args:
        - BASE_PATH=$TENANT_BASE_PATH
    image: mre/tenant-frontend:latest
    environment:
      - NODE_ENV
      - PORT=$TENANT_FRONTEND_PORT
      - LOGGER_LEVEL=$LOGGER_LEVEL
      - APP_NAME=$APP_NAME
      - BASE_PATH=$TENANT_BASE_PATH
      - API_URL=$API_URL
      - APP_URL=$TENANT_APP_URL
      - DOCKER_API_URL=$DOCKER_API_URL
      - REFRESH_TOKEN_SECRET=$AUTHENTICATOR_REFRESH_TOKEN_SECRET
      - DEMO_MODE=$DEMO_MODE
      - CORS_ENABLED=$CORS_ENABLED
    expose:
      - '$TENANT_FRONTEND_PORT'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - net
    depends_on:
      - gateway
###############################################################################
# microservices network
###############################################################################
networks:
  net:
    driver: bridge
